apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: qdash-system
resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
# Create a real secret based on secret.example.yaml and include it here.
